name: CI/CD Pipeline

on:
  push:
    branches:
      - backend # Runs only on pushes to the 'backend' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploying to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd coordinateApp
            git checkout backend
            git pull
            npm install
            pm2 reload all
